In [43]:
import pandas as pd
from sklearn import linear_model
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures

In [44]:
df=pd.read_csv('CarData.csv')

In [45]:
df.head(5)

Car_Name  Year  Current_price  Selling_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [50]:
#polynomiaal_features = PolynomialFeatures(degree=2)
#input_dimension_polynomic = polynomiaal_features.fit_transform(df[['Current_price']])
#regression_tool = linear_model.LinearRegression()
#regression_tool.fit(input_dimension_polynomic, df['Selling_Price'])  #input_dimension_polynomic
#regression_tool.fit(data_frame[['trip_length','trip_time']], data_frame['trip_price'])


#plt.title('Current_price Vs Selling_Price', fontsize=14)
#plt.xlabel('Selling_Price', fontsize=14)
#plt.ylabel('Current_price', fontsize=14)
#plt.grid(True)
#plt.scatter(df['Selling_Price'], df['Current_price'])
regression_tool = linear_model.LinearRegression()
regression_tool.fit(df[['Selling_Price']], df['Current_price'])
regression_curve = regression_tool.predict(df[['Selling_Price']])
#plt.plot(df['Selling_Price'], regression_curve, color='b')
#plt.show()

#plt.title('number_of_observations vs. month_n', fontsize=14)
#plt.xlabel('number_of_observations', fontsize=14)
#plt.ylabel('month_n', fontsize=14)
#plt.grid(True)

#plt.scatter(df['number_of_observations'], df['month_n'])

#regression_tool = linear_model.LinearRegression()
#regression_tool.fit(df[['number_of_observations']], df['month_n'])

#regression_curve = regression_tool.predict(df[['number_of_observations']])
#plt.plot(df['number_of_observations'], regression_curve, color='y')

#plt.show()
#regression_tool = linear_model.LinearRegression()
#regression_tool.fit(df[['Kms_Driven','Year']], df['Current_price'])



In [51]:
#regression_tool.fit(df[['Selling_Price']], df['Current_price'])
#'Year','Kms_Driven'

In [52]:
#regression_curve = regression_tool.predict(df[['Current_price']])
#,'Year','Kms_Driven'

In [53]:
from sklearn.metrics import r2_score
current_price_r2_score=r2_score(df['Current_price'], regression_curve)

print("R2 score:",current_price_r2_score)

R2 score: 0.7726103146985799


In [37]:
def adj_r2(df, r2):
    #Adjusted RSquared of the model
    
    n=len(df) #number of records
    p=len(df.columns)-2 #number of features .i.e. columns excluding uniqueId and target variable
    return 1-(1-r2)*(n-1)/(n-p-1) # the mathematical formula for calculating adjusted r2.

In [38]:
adjusted_r2 = adj_r2(df, current_price_r2_score)

print(adjusted_r2)

0.6674681083732181


In [234]:
from sklearn.preprocessing import OneHotEncoder

In [240]:
encoder = OneHotEncoder(sparse=False)
onehot = encoder.fit_transform(df)

In [241]:
print(onehot)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
