In [536]:
import numpy as np

In [484]:
my_array1 = np.array([1,2,3,4])
print(my_array1)

[1 2 3 4]


In [485]:
print(my_array1[1])

2


In [486]:
print(my_array1[2])

3


In [487]:
print(my_array1[0])

1


In [488]:
my_array2 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
print(my_array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [489]:
print(my_array2[0,2])

3


In [490]:
print(my_array2[0,0])

1


In [491]:
print(my_array2[2,2])

11


In [492]:
print(my_array2[1,0])

5


In [493]:
sheet1 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
sheet2 = np.array( [[13,14,15,16],[17,18,19,20],[21,22,23,24]] )
sheet3 = np.array( [[25,26,27,28],[29,30,31,32],[33,34,35,36]] )

my_array3=np.array([sheet1,sheet2,sheet3])
print(my_array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [494]:
print(my_array3[0,0,2])

3


In [495]:
print(my_array3[0,0,0])

1


In [496]:
print(my_array3[1,2,3])

24


In [497]:
print(my_array3[2,2,2])

35


In [498]:
print(my_array3[1,1,2])

19


In [499]:
print(my_array3[1,1,1])

18


In [500]:
print(my_array3[0,2,3])

12


In [501]:
sheet1 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
sheet2 = np.array( [[13,14,15,16],[17,18,19,20],[21,22,23,24]] )
sheet3 = np.array( [[25,26,27,28],[29,30,31,32],[33,34,35,36]] )
workbook1=np.array([sheet1,sheet2,sheet3])

sheet4 = np.array( [[37,38,39,40],[41,42,43,44],[45,46,47,48]] )
sheet5 = np.array( [[49,50,51,52],[53,54,55,56],[57,58,59,60]] )
sheet6 = np.array( [[61,62,63,64],[65,66,67,68],[69,70,71,72]] )
workbook2=np.array([sheet4,sheet5,sheet6])

sheet7 = np.array( [[73,74,75,76],[77,78,79,80],[81,82,83,84]] )
sheet8 = np.array( [[85,86,87,88],[89,90,91,92],[93,94,95,96]] )
sheet9 = np.array( [[97,98,99,100],[101,102,103,104],[105,106,107,108]] )
workbook3=np.array([sheet7,sheet8,sheet9])

my_array4=np.array([workbook1,workbook2,workbook3])

print(my_array4)

[[[[  1   2   3   4]
   [  5   6   7   8]
   [  9  10  11  12]]

  [[ 13  14  15  16]
   [ 17  18  19  20]
   [ 21  22  23  24]]

  [[ 25  26  27  28]
   [ 29  30  31  32]
   [ 33  34  35  36]]]


 [[[ 37  38  39  40]
   [ 41  42  43  44]
   [ 45  46  47  48]]

  [[ 49  50  51  52]
   [ 53  54  55  56]
   [ 57  58  59  60]]

  [[ 61  62  63  64]
   [ 65  66  67  68]
   [ 69  70  71  72]]]


 [[[ 73  74  75  76]
   [ 77  78  79  80]
   [ 81  82  83  84]]

  [[ 85  86  87  88]
   [ 89  90  91  92]
   [ 93  94  95  96]]

  [[ 97  98  99 100]
   [101 102 103 104]
   [105 106 107 108]]]]


In [502]:
print(my_array4[0,0,0,2])

3


In [503]:
print(my_array4[0,0,0,0])

1


In [504]:
print(my_array4[0,1,0,0])

13


In [505]:
print(my_array4[2,0,0,0])

73


In [506]:
print(my_array4[1,1,1,3])

56


In [507]:
print(my_array4[2,1,0,0])

85


In [508]:
print(my_array4[2,2,2,3])

108


In [509]:
my_array0 = np.array([109])

In [510]:
print(my_array0[0])

109


In [511]:
one_array=np.array([23,63,45,89])

In [512]:
print(one_array[3])

89


In [513]:
two_array=np.array([45,66,78,12,34,48,22,92])

In [514]:
print(two_array[1])

66


In [515]:
twod_array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [516]:
print(twod_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [517]:
my_array=np.array([range(4),reversed(range(4))])
print(my_array)

[range(0, 4) <range_iterator object at 0x7f24bc004e10>]


<ipython-input-517-068e79237f03>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  my_array=np.array([range(4),reversed(range(4))])


In [518]:
range_array1=np.array([range(4),range(4,8)])

In [519]:
print(range_array1)

[[0 1 2 3]
 [4 5 6 7]]


In [520]:
range_array1=np.array([range(4)])
x = np.array([range(1,5)])
range_array2=np.flip(x)
concatenated=np.concatenate((range_array1, range_array2))

In [521]:
print(concatenated)

[[0 1 2 3]
 [4 3 2 1]]


In [537]:
my_array1=np.array([range(8)])
my_array2=np.array([range(1,9)])
flipped_array=np.flip(my_array2)

In [538]:
concated_array=np.concatenate((my_array1, flipped_array))
reashaped_array=concated_array.reshape(4,4)

In [540]:
print(reashaped_array)

[[0 1 2 3]
 [4 5 6 7]
 [8 7 6 5]
 [4 3 2 1]]


In [525]:
my_array1=np.array([range(0,16,2)])
my_array2=np.array([range(2,18,2)])
print(my_array1, my_array2)

[[ 0  2  4  6  8 10 12 14]] [[ 2  4  6  8 10 12 14 16]]


In [526]:
flipped=np.flip(my_array2)

In [527]:
concatenated=np.concatenate((my_array1, flipped))

In [528]:
print(concatenated)

[[ 0  2  4  6  8 10 12 14]
 [16 14 12 10  8  6  4  2]]


In [529]:
concatenated.reshape(4,4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

In [530]:
my_array1=np.array([[range(0,100,10)]])
my_array2=np.array([[range(100,1100,100)]])
print(my_array1, my_array2)

[[[ 0 10 20 30 40 50 60 70 80 90]]] [[[ 100  200  300  400  500  600  700  800  900 1000]]]


In [531]:
my_array3=np.array([[range(0,100,10)]])
my_array4=np.array([[range(100,1100,100)]])

In [532]:
print(my_array3, my_array4)

[[[ 0 10 20 30 40 50 60 70 80 90]]] [[[ 100  200  300  400  500  600  700  800  900 1000]]]


In [533]:
flipped1=np.flip(my_array3)

In [534]:
flipped2=np.flip(my_array4)

In [535]:
concatenated=np.concatenate((my_array1, my_array2, flipped2, flipped1))

In [482]:
print(concatenated)

[[[   0   10   20   30   40   50   60   70   80   90]]

 [[ 100  200  300  400  500  600  700  800  900 1000]]

 [[1000  900  800  700  600  500  400  300  200  100]]

 [[  90   80   70   60   50   40   30   20   10    0]]]
