In [21]:
import numpy as np

In [22]:
my_array1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
my_slice=my_array1[2:6]
print(my_slice)

[3 4 5 6]


In [24]:
my_slice=my_array1[0:3]
print(my_slice)

[1 2 3]


In [25]:
my_slice=my_array1[7:10]
print(my_slice)

[ 8  9 10]


In [26]:
my_slice=my_array1[0:9:2]
print(my_slice)

[1 3 5 7 9]


In [27]:
my_slice=my_array1[5:10:2]
print(my_slice)

[ 6  8 10]


In [44]:
my_slice=my_array1[-9:-1:3]
print(my_slice)

[2 5 8]


In [43]:
my_slice=my_array1[-5::2]
print(my_slice)

[ 6  8 10]


In [39]:
my_slice=my_array1[-8:-2:2]
print(my_slice)

[3 5 7]


In [46]:
my_slice=my_array1[-3:]
print(my_slice)

[ 8  9 10]


In [54]:
my_array2 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
print(my_array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
my_slice=my_array2[1,1:4]

In [58]:
print(my_slice)

[6 7 8]


In [59]:
my_slice=my_array2[2,0:4:2]

In [60]:
print(my_slice)

[ 9 11]


In [84]:
my_slice=my_array2[0:3,0:13:2]

In [85]:
print(my_slice)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [86]:
my_slice=my_array2[0:3,0:13:3]

In [87]:
print(my_slice)

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [127]:
my_slice=my_array2[:,-2:]

In [128]:
print(my_slice)

[[ 3  4]
 [ 7  8]
 [11 12]]


In [132]:
my_slice=my_array2[:,-3:-1]

In [133]:
print(my_slice)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [154]:
my_slice=my_array2[:,-3::2]

In [155]:
print(my_slice)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [2]:
import numpy as np
sheet1 = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]] )
sheet2 = np.array( [[13,14,15,16],[17,18,19,20],[21,22,23,24]] )
sheet3 = np.array( [[25,26,27,28],[29,30,31,32],[33,34,35,36]] )

my_array=np.array([sheet1,sheet2,sheet3])
print(my_array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [3]:
my_slice=my_array[0, 2, 0:3]

In [4]:
print(my_slice)

[ 9 10 11]


In [161]:
my_slice=my_array3[2,1,1:4:2]

In [162]:
print(my_slice)

[30 32]


In [211]:
my_slice=my_array3[2,:,::2]

In [212]:
print(my_slice)

[[25 27]
 [29 31]
 [33 35]]


In [217]:
my_slice=my_array3[1,:,::3]

In [218]:
print(my_slice)

[[13 16]
 [17 20]
 [21 24]]


In [257]:
my_slice=my_array3[-2,:, -2:5]

In [258]:
print(my_slice)

[[15 16]
 [19 20]
 [23 24]]


In [306]:
my_slice=my_array3[-2:,:, -3::2]

In [307]:
print(my_slice)

[[[14 16]
  [18 20]
  [22 24]]

 [[26 28]
  [30 32]
  [34 36]]]
